apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "astera-runtime.fullname" . }}
  labels:
    {{- include "astera-runtime.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "astera-runtime.name" . }}
